import type  { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
import Image from "next/image";
import Navbar from "../components/navbar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// interface MenuItem {
//   path: string;
//   label: string;
//   activeClass?: string;
//   hasDropdown?: boolean;
// }

// interface LinkItem {
//   href: string;
//   label: string;
//   icon: string;
// }
const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {

  // const pathname = usePathname();
  // const brand = pathname.split("/")[3];
  // console.log(brand);
  
  // useEffect(() => {
  //   const fetchMenuData = async () => {
  //     try {
  //       const response = await fetch(`/api/navbar?endpoint=${pathname}`);
  //       const data = await response.json();
  //       setMenuItems(data.menuItems || []);
  //       setLinks(data.links || []);
  //     } catch (error) {
  //       console.error('Failed to fetch navbar data:', error);
  //     }
  //   };

  //   fetchMenuData();
  // }, [brand]);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-50`}
      >

        <Header />
        <Image
          width={0}
          height={5}
          sizes="100vw"
          className="object-none  w-full "
          src={'https://tpc.googlesyndication.com/simgad/2186141005922165001'} alt='' />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
export default RootLayout;